import React, { useState, useCallback } from "react";

/**
 * Opens a new browser window with a print-ready Section 65B verification
 * certificate and triggers the print dialog.
 */
function printCertificate({ docHash, onChain, offChain }) {
  const now        = new Date().toLocaleString();
  const anchored   = onChain ? new Date(onChain.timestamp * 1000).toLocaleString() : "N/A";
  const issuer     = onChain?.issuer  ?? "N/A";
  const ipfsHash   = onChain?.ipfsHash ?? "";
  const ipfsCid    = (ipfsHash && ipfsHash !== "ipfs_placeholder") ? ipfsHash : (offChain?.ipfsCid ?? "");
  const fileName   = offChain?.fileName   ?? "Unknown";
  const aiScore    = offChain?.aiScore    != null ? `${offChain.aiScore.toFixed(1)}%` : "N/A";
  const aiProvider = offChain?.aiProvider ?? "N/A";

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Verification Certificate</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Inter, 'Segoe UI', sans-serif; color: #1a1a2e; background: #fff; padding: 40px; max-width: 760px; margin: 0 auto; }
    .cert-header { text-align: center; border-bottom: 3px double #1a1a2e; padding-bottom: 20px; margin-bottom: 28px; }
    .cert-logo { font-size: 1.8rem; font-weight: 700; letter-spacing: -0.5px; color: #1a6ef5; }
    .cert-title { font-size: 1.1rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.12em; margin-top: 6px; }
    .cert-subtitle { font-size: 0.8rem; color: #555; margin-top: 4px; }
    .section { margin-bottom: 22px; }
    .section-title { font-size: 0.72rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #888; border-bottom: 1px solid #ddd; padding-bottom: 4px; margin-bottom: 10px; }
    .row { display: flex; gap: 8px; padding: 5px 0; font-size: 0.875rem; border-bottom: 1px solid #f0f0f0; }
    .row:last-child { border-bottom: none; }
    .label { width: 170px; flex-shrink: 0; color: #555; font-weight: 600; }
    .value { color: #1a1a2e; word-break: break-all; font-family: 'SFMono-Regular', Consolas, monospace; font-size: 0.82rem; }
    .value.normal { font-family: inherit; font-size: 0.875rem; }
    .disclaimer { margin-top: 28px; padding: 16px; background: #f8f8f8; border-left: 4px solid #1a6ef5; font-size: 0.8rem; color: #444; line-height: 1.6; }
    .cert-footer { margin-top: 32px; text-align: center; font-size: 0.72rem; color: #aaa; border-top: 1px solid #ddd; padding-top: 16px; }
    @media print { body { padding: 20mm; } button { display: none !important; } }
  </style>
</head>
<body>
  <div class="cert-header">
    <div class="cert-logo">DocVerify</div>
    <div class="cert-title">Digital Document Verification Certificate</div>
    <div class="cert-subtitle">Blockchain Integrity Proof &mdash; Ethereum Sepolia Testnet</div>
  </div>

  <div class="section">
    <div class="section-title">Document Identification</div>
    <div class="row"><span class="label">File Name</span><span class="value normal">${fileName}</span></div>
    <div class="row"><span class="label">SHA-256 Fingerprint</span><span class="value">${docHash}</span></div>
    ${ipfsCid ? `<div class="row"><span class="label">IPFS CID</span><span class="value">${ipfsCid}</span></div>` : ""}
  </div>

  <div class="section">
    <div class="section-title">On-Chain Record</div>
    <div class="row"><span class="label">Issuer (Ethereum)</span><span class="value">${issuer}</span></div>
    <div class="row"><span class="label">Anchored On</span><span class="value normal">${anchored}</span></div>
    <div class="row"><span class="label">Smart Contract</span><span class="value">See verifier-client/src/config/contract.js</span></div>
    <div class="row"><span class="label">Network</span><span class="value normal">Ethereum Sepolia Testnet (Chain ID: 11155111)</span></div>
  </div>

  <div class="section">
    <div class="section-title">AI Authenticity Check</div>
    <div class="row"><span class="label">Fake-Content Score</span><span class="value normal">${aiScore}</span></div>
    <div class="row"><span class="label">AI Provider</span><span class="value normal">${aiProvider}</span></div>
  </div>

  <div class="section">
    <div class="section-title">Certificate Metadata</div>
    <div class="row"><span class="label">Generated At</span><span class="value normal">${now}</span></div>
    <div class="row"><span class="label">Verification Status</span><span class="value normal">AUTHENTIC &mdash; Hash found on immutable ledger</span></div>
  </div>

  <div class="disclaimer">
    <strong>Certificate of Authenticity — Indian Evidence Act, Section 65B Statement</strong><br/><br/>
    This certificate is generated by the DocVerify blockchain verification system. The above SHA-256
    fingerprint was found to be present on the Ethereum Sepolia blockchain at the stated timestamp.
    The cryptographic hash was recorded by the stated issuer wallet and has not been altered since
    inscription. This certificate may be used as supporting documentation under Section 65B of the
    Indian Evidence Act, 1872, as an electronic record certified by the system responsible for its
    production. The immutable nature of the Ethereum blockchain provides a tamper-evident chain of
    custody for the above document fingerprint.
  </div>

  <div class="cert-footer">
    Generated by DocVerify &bull; Blockchain-Based Digital Content Authenticity System &bull; ${now}
  </div>
</body>
</html>`;

  const win = window.open("", "_blank", "width=840,height=900");
  if (!win) return; // blocked by popup blocker
  win.document.write(html);
  win.document.close();
  win.onload = () => win.print();
}

/**
 * Small inline copy-to-clipboard button.
 * Shows a checkmark for 1.5 s after a successful copy, then resets.
 */
function CopyButton({ text }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      // Clipboard API unavailable — silently ignore
    }
  }, [text]);

  return (
    <button
      className={`copy-btn ${copied ? "copy-btn-copied" : ""}`}
      onClick={handleCopy}
      title={copied ? "Copied!" : "Copy to clipboard"}
      aria-label={copied ? "Copied" : "Copy"}
    >
      {copied ? "✓" : "⎘"}
    </button>
  );
}

function formatAddress(addr) {
  return `${addr.slice(0, 6)}…${addr.slice(-4)}`;
}

function formatTimestamp(unixSeconds) {
  return new Date(unixSeconds * 1000).toLocaleString();
}

/**
 * ResultCard
 *
 * Props:
 *   docHash  {string}        — 0x-prefixed SHA-256 hex hash
 *   onChain  {object|null}   — { issuer, timestamp, ipfsHash } from verifyDocument(), or null if not found
 *   offChain {object|null}   — { fileName, aiScore, isAuthentic, createdAt } from /api/document/:hash, or null
 *   revoked  {boolean}       — true when isRevoked() returns true for this hash
 */
function ResultCard({ docHash, onChain, offChain, revoked = false }) {
  const found           = onChain !== null;
  const isAuthentic     = found && !revoked;
  const [showAiDetails, setShowAiDetails] = useState(false);

  const cardClass = !found
    ? "result-tampered"
    : revoked
    ? "result-revoked"
    : "result-authentic";

  const badgeText = !found
    ? "✗ NOT VERIFIED"
    : revoked
    ? "⚠ REVOKED"
    : "✓ AUTHENTIC";

  return (
    <div className={`result-card ${cardClass}`}>
      <div className="result-badge">
        {badgeText}
      </div>

      <div className="result-body">
        {/* File hash */}
        <div className="result-row">
          <span className="result-label">File Hash</span>
          <span className="result-value">
            <code>{docHash}</code>
            <CopyButton text={docHash} />
          </span>
        </div>

        {/* On-chain data — shown whether authentic or revoked, so the issuer is always visible */}
        {found && onChain && (
          <>
            <div className="result-row">
              <span className="result-label">Issuer</span>
              <span className="result-value">
                <a
                  href={`https://sepolia.etherscan.io/address/${onChain.issuer}`}
                  target="_blank"
                  rel="noreferrer"
                >
                  {formatAddress(onChain.issuer)}
                </a>
                <CopyButton text={onChain.issuer} />
              </span>
            </div>

            <div className="result-row">
              <span className="result-label">Anchored On</span>
              <span className="result-value">{formatTimestamp(onChain.timestamp)}</span>
            </div>

            {/* Show IPFS link — prefer on-chain CID, fall back to off-chain record */}
            {(() => {
              const cid = (onChain.ipfsHash && onChain.ipfsHash !== "ipfs_placeholder")
                ? onChain.ipfsHash
                : offChain?.ipfsCid || null;
              return cid ? (
                <div className="result-row">
                  <span className="result-label">IPFS</span>
                  <span className="result-value">
                    <a
                      href={`https://gateway.pinata.cloud/ipfs/${cid}`}
                      target="_blank"
                      rel="noreferrer"
                    >
                      {cid}
                    </a>
                  </span>
                </div>
              ) : null;
            })()}
          </>
        )}

        {/* Off-chain metadata (best-effort — may be absent) */}
        {offChain && (
          <>
            <div className="result-divider" />
            <p className="result-section-title">Off-chain metadata</p>

            {offChain.fileName && (
              <div className="result-row">
                <span className="result-label">File Name</span>
                <span className="result-value">{offChain.fileName}</span>
              </div>
            )}

            {offChain.aiScore != null && (
              <div className="result-row">
                <span className="result-label">AI Score</span>
                <span className="result-value">
                  {offChain.aiScore.toFixed(1)}% fake probability
                  {offChain.aiProvider && !offChain.aiProvider.startsWith('mock') ? (
                    <span className="ai-badge ai-badge-live">● live check</span>
                  ) : (
                    <span className="ai-badge ai-badge-mock">● mock</span>
                  )}
                </span>
              </div>
            )}

            {offChain.aiProvider && (
              <div className="result-row">
                <span className="result-label">AI Provider</span>
                <span className="result-value">{offChain.aiProvider}</span>
              </div>
            )}

            {offChain.createdAt && (
              <div className="result-row">
                <span className="result-label">Recorded At</span>
                <span className="result-value">
                  {new Date(offChain.createdAt).toLocaleString()}
                </span>
              </div>
            )}
          </>
        )}

        {/* Not-found explanation */}
        {!found && (
          <p className="result-not-found">
            No on-chain record was found for this file's fingerprint. The document may have been
            tampered with, or it was never registered on this system.
          </p>
        )}

        {/* AI provider details (Eden AI breakdown, if available) */}
        {offChain?.aiDetails && !offChain.aiProvider?.startsWith('mock') && (
          <>
            <div className="result-divider" />
            <button
              className="ai-details-toggle"
              onClick={() => setShowAiDetails(v => !v)}
            >
              {showAiDetails ? "▾ Hide AI Details" : "▸ Show AI Details"}
            </button>
            {showAiDetails && (
              <div className="ai-details-box">
                {offChain.aiDetails.ai_score != null && (
                  <div className="result-row">
                    <span className="result-label">Raw AI Score</span>
                    <span className="result-value">{(offChain.aiDetails.ai_score * 100).toFixed(2)}%</span>
                  </div>
                )}
                {Array.isArray(offChain.aiDetails.items) && offChain.aiDetails.items.length > 0 && (
                  <div className="result-row">
                    <span className="result-label">Detection Items</span>
                    <span className="result-value">
                      <pre className="ai-details-pre">
                        {JSON.stringify(offChain.aiDetails.items, null, 2)}
                      </pre>
                    </span>
                  </div>
                )}
                {offChain.aiDetails.cost != null && (
                  <div className="result-row">
                    <span className="result-label">API Cost</span>
                    <span className="result-value">${offChain.aiDetails.cost}</span>
                  </div>
                )}
              </div>
            )}
          </>
        )}

        {/* Section 65B Verification Certificate */}
        {isAuthentic && (
          <div style={{ marginTop: "16px" }}>
            <button
              className="btn btn-secondary"
              style={{ fontSize: "0.82rem", padding: "8px 16px" }}
              onClick={() => printCertificate({ docHash, onChain, offChain })}
            >
              ⬇ Download Verification Certificate
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

export default ResultCard;
