'use strict';
/**
 * fabric/gateway.js
 * Hyperledger Fabric gateway with multi-organization support for DocVerifier.
 *
 * Uses @hyperledger/fabric-gateway (v1.x) + @grpc/grpc-js.
 * Reads TLS and signing credentials from the crypto-config/ generated by
 * setup-multi-org-network.sh (cryptogen).
 *
 * SUPPORTS MULTIPLE ORGANIZATIONS:
 * - Org1MSP (default, host org at localhost:7051)
 * - Org2MSP (partner at localhost:8051)
 * - Org3MSP (partner at localhost:9051)
 * - Additional orgs can be added via environment variables
 *
 * Environment variables (optional overrides):
 *   FABRIC_MSP_ID          default: "Org1MSP"
 *   FABRIC_CHANNEL         default: "mychannel"
 *   FABRIC_CHAINCODE       default: "docverifier"
 *
 * For custom org endpoints, use org-specific env vars:
 *   FABRIC_ORG2_PEER_ENDPOINT   default: "localhost:8051"
 *   FABRIC_ORG2_PEER_HOST_ALIAS default: "peer0.org2.example.com"
 *
 * Usage (Single Org - Default Org1MSP):
 *   const { getContract, closeGateway } = require('./gateway');
 *   const contract = await getContract();
 *   await contract.submitTransaction('AnchorDocument', docHash, ipfsCid);
 *
 * Usage (Multi-Org - Select by MSP ID):
 *   const { getContractForOrg, closeGateway } = require('./gateway');
 *   const contract = await getContractForOrg('Org2MSP');
 *   await contract.submitTransaction('AnchorDocument', docHash, ipfsCid);
 */

const { connect, signers } = require('@hyperledger/fabric-gateway');
const grpc   = require('@grpc/grpc-js');
const crypto = require('crypto');
const path   = require('path');
const { promises: fs } = require('fs');

// ── Paths ─────────────────────────────────────────────────────────────────────
const FABRIC_DIR = path.resolve(__dirname, '../../fabric');
const CRYPTO_DIR = path.join(FABRIC_DIR, 'crypto-config');

// ── Organization configuration (name -> config) ────────────────────────────────
const ORG_CONFIG = {
  'Org1MSP': {
    name: 'Org1',
    domain: 'org1.example.com',
    peerPort: 7051,
    peerAlias: 'peer0.org1.example.com',
    defaultPeerEndpoint: 'localhost:7051'
  },
  'Org2MSP': {
    name: 'Org2',
    domain: 'org2.example.com',
    peerPort: 8051,
    peerAlias: 'peer0.org2.example.com',
    defaultPeerEndpoint: 'localhost:8051'
  },
  'Org3MSP': {
    name: 'Org3',
    domain: 'org3.example.com',
    peerPort: 9051,
    peerAlias: 'peer0.org3.example.com',
    defaultPeerEndpoint: 'localhost:9051'
  }
};

// ── Singleton state (caching gateways per org) ────────────────────────────────
const _gateways = {}; // Map of mspId -> { gateway, client }

// ── Helpers ───────────────────────────────────────────────────────────────────
async function firstFileIn(dir) {
  const entries = await fs.readdir(dir);
  const files   = entries.filter(f => !f.startsWith('.'));
  if (!files.length) throw new Error(`No file found in ${dir}`);
  return path.join(dir, files[0]);
}

/**
 * Get organization config by MSP ID
 * @param {string} mspId - e.g., 'Org1MSP', 'Org2MSP', 'Org3MSP'
 * @returns {object} Organization configuration
 * @throws Error if organization not found
 */
function getOrgConfig(mspId) {
  const config = ORG_CONFIG[mspId];
  if (!config) {
    const available = Object.keys(ORG_CONFIG).join(', ');
    throw new Error(`Organization ${mspId} not configured. Available: ${available}`);
  }
  return config;
}

/**
 * Build a gateway for a specific organization
 * @param {string} mspId - Organization MSP ID (e.g., 'Org1MSP')
 * @returns {object} { gateway, client }
 */
async function buildGatewayForOrg(mspId) {
  const orgConfig = getOrgConfig(mspId);
  const orgName   = orgConfig.name;
  const domain    = orgConfig.domain;
  const peerAlias = orgConfig.peerAlias;

  // Construct paths based on org
  const orgDir    = path.join(CRYPTO_DIR, 'peerOrganizations', domain);
  const adminMsp  = path.join(orgDir, 'users', `Admin@${domain}`, 'msp');
  const peerTls   = path.join(orgDir, 'peers', peerAlias, 'tls', 'ca.crt');

  // Verify crypto material exists
  try {
    await fs.access(peerTls);
  } catch {
    throw new Error(
      `Fabric crypto material not found for ${mspId}. ` +
      'Run fabric/scripts/setup-multi-org-network.sh to bootstrap the network first.\n' +
      `Expected TLS cert at: ${peerTls}`
    );
  }

  // Get peer endpoint (from env or default)
  const orgNameUpper = orgName.toUpperCase();
  const envKey = `FABRIC_${orgNameUpper}_PEER_ENDPOINT`;
  const peerEndpoint = process.env[envKey] || orgConfig.defaultPeerEndpoint;

  // gRPC client with TLS
  const tlsCert   = await fs.readFile(peerTls);
  const creds     = grpc.credentials.createSsl(tlsCert);
  const client = new grpc.Client(peerEndpoint, creds, {
    'grpc.ssl_target_name_override': peerAlias,
    'grpc.max_receive_message_length': 10 * 1024 * 1024 // 10 MB
  });

  // Identity: Admin certificate
  const certDir  = path.join(adminMsp, 'signcerts');
  const certFile = await firstFileIn(certDir);
  const certPem  = await fs.readFile(certFile);

  // Signer: Admin private key
  const keyFile    = await firstFileIn(path.join(adminMsp, 'keystore'));
  const keyPem     = await fs.readFile(keyFile, 'utf8');
  const privateKey = crypto.createPrivateKey(keyPem);

  // Build gateway
  const gateway = connect({
    client,
    identity: { mspId, credentials: certPem },
    signer: signers.newPrivateKeySigner(privateKey),
    // Evaluation (query) timeout: 5s; Endorsement: 15s; Broadcast: 5s; Commit: 60s
    evaluateOptions:   () => ({ deadline: Date.now() + 5_000  }),
    endorseOptions:    () => ({ deadline: Date.now() + 15_000 }),
    submitOptions:     () => ({ deadline: Date.now() + 5_000  }),
    commitStatusOptions: () => ({ deadline: Date.now() + 60_000 })
  });

  console.log(`[Fabric] Gateway connected for ${mspId} at ${peerEndpoint}`);
  return { gateway, client };
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Returns a chaincode Contract handle for a specific organization.
 * Lazily builds the gateway on first call.
 *
 * @param {string} mspId - Organization MSP ID (default: from env or 'Org1MSP')
 * @returns {Promise<Contract>} Fabric chaincode contract
 */
async function getContractForOrg(mspId) {
  // Use provided mspId or fall back to environment/default
  const orgId = mspId || process.env.FABRIC_MSP_ID || 'Org1MSP';

  // Lazy build gateway for this org
  if (!_gateways[orgId]) {
    _gateways[orgId] = await buildGatewayForOrg(orgId);
  }

  const { gateway } = _gateways[orgId];
  const channel  = process.env.FABRIC_CHANNEL   || 'mychannel';
  const ccName   = process.env.FABRIC_CHAINCODE  || 'docverifier';
  const network  = gateway.getNetwork(channel);
  return network.getContract(ccName);
}

/**
 * Backward compatibility: Gets contract for default org (Org1MSP)
 * @returns {Promise<Contract>} Fabric chaincode contract
 */
async function getContract() {
  return getContractForOrg();
}

/**
 * Cleanly closes all gRPC connections and gateways.
 * Call during process shutdown.
 */
function closeGateway() {
  Object.entries(_gateways).forEach(([mspId, { gateway, client }]) => {
    if (gateway) gateway.close();
    if (client) client.close();
    console.log(`[Fabric] Gateway closed for ${mspId}`);
  });
  Object.keys(_gateways).forEach(key => delete _gateways[key]);
}

/**
 * Get list of available organizations
 * @returns {array} Array of MSP IDs
 */
function getAvailableOrganizations() {
  return Object.keys(ORG_CONFIG);
}

module.exports = {
  getContract,
  getContractForOrg,
  closeGateway,
  getAvailableOrganizations,
  ORG_CONFIG
};
