'use strict';
/**
 * fabric/gateway.js
 * Hyperledger Fabric gateway singleton for DocVerifier.
 *
 * Uses @hyperledger/fabric-gateway (v1.x) + @grpc/grpc-js.
 * Reads TLS and signing credentials from the crypto-config/ generated by
 * start-network.sh (cryptogen).
 *
 * Environment variables (optional overrides):
 *   FABRIC_PEER_ENDPOINT   default: "localhost:7051"
 *   FABRIC_PEER_HOST_ALIAS default: "peer0.org1.example.com"
 *   FABRIC_MSP_ID          default: "Org1MSP"
 *   FABRIC_CHANNEL         default: "mychannel"
 *   FABRIC_CHAINCODE       default: "docverifier"
 *
 * Usage:
 *   const { getContract, closeGateway } = require('./gateway');
 *   const contract = await getContract();
 *   await contract.submitTransaction('AnchorDocument', docHash, ipfsCid);
 */

const { connect, signers } = require('@hyperledger/fabric-gateway');
const grpc   = require('@grpc/grpc-js');
const crypto = require('crypto');
const path   = require('path');
const { promises: fs } = require('fs');

// ── Paths ─────────────────────────────────────────────────────────────────────
const FABRIC_DIR = path.resolve(__dirname, '../../fabric');
const CRYPTO_DIR = path.join(FABRIC_DIR, 'crypto-config');
const ORG1_DIR   = path.join(CRYPTO_DIR, 'peerOrganizations', 'org1.example.com');
const ADMIN_MSP  = path.join(ORG1_DIR, 'users', 'Admin@org1.example.com', 'msp');
const PEER_TLS   = path.join(ORG1_DIR, 'peers', 'peer0.org1.example.com', 'tls', 'ca.crt');

// ── Singleton state ───────────────────────────────────────────────────────────
let _gateway = null;
let _client  = null;

// ── Helpers ───────────────────────────────────────────────────────────────────
async function firstFileIn(dir) {
  const entries = await fs.readdir(dir);
  const files   = entries.filter(f => !f.startsWith('.'));
  if (!files.length) throw new Error(`No file found in ${dir}`);
  return path.join(dir, files[0]);
}

// ── Build the gateway (called lazily) ─────────────────────────────────────────
async function buildGateway() {
  // Verify crypto material exists before attempting connection
  try {
    await fs.access(PEER_TLS);
  } catch {
    throw new Error(
      'Fabric crypto material not found. ' +
      'Run fabric/scripts/start-network.sh to bootstrap the network first.\n' +
      `Expected TLS cert at: ${PEER_TLS}`
    );
  }

  const peerEndpoint = process.env.FABRIC_PEER_ENDPOINT   || 'localhost:7051';
  const peerAlias    = process.env.FABRIC_PEER_HOST_ALIAS  || 'peer0.org1.example.com';
  const mspId        = process.env.FABRIC_MSP_ID           || 'Org1MSP';

  // gRPC client with TLS
  const tlsCert   = await fs.readFile(PEER_TLS);
  const creds     = grpc.credentials.createSsl(tlsCert);
  _client = new grpc.Client(peerEndpoint, creds, {
    'grpc.ssl_target_name_override': peerAlias,
    'grpc.max_receive_message_length': 10 * 1024 * 1024 // 10 MB
  });

  // Identity: Admin certificate
  const certDir  = path.join(ADMIN_MSP, 'signcerts');
  const certFile = await firstFileIn(certDir);
  const certPem  = await fs.readFile(certFile);

  // Signer: Admin private key
  const keyFile    = await firstFileIn(path.join(ADMIN_MSP, 'keystore'));
  const keyPem     = await fs.readFile(keyFile, 'utf8');
  const privateKey = crypto.createPrivateKey(keyPem);

  _gateway = connect({
    client: _client,
    identity: { mspId, credentials: certPem },
    signer: signers.newPrivateKeySigner(privateKey),
    // Evaluation (query) timeout: 5s; Endorsement: 15s; Broadcast: 5s; Commit: 60s
    evaluateOptions:   () => ({ deadline: Date.now() + 5_000  }),
    endorseOptions:    () => ({ deadline: Date.now() + 15_000 }),
    submitOptions:     () => ({ deadline: Date.now() + 5_000  }),
    commitStatusOptions: () => ({ deadline: Date.now() + 60_000 })
  });

  console.log('[Fabric] Gateway connected to', peerEndpoint);
  return _gateway;
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Returns a chaincode Contract handle.
 * Lazily builds the gateway on first call.
 */
async function getContract() {
  if (!_gateway) await buildGateway();
  const channel  = process.env.FABRIC_CHANNEL   || 'mychannel';
  const ccName   = process.env.FABRIC_CHAINCODE  || 'docverifier';
  const network  = _gateway.getNetwork(channel);
  return network.getContract(ccName);
}

/**
 * Cleanly closes the gRPC connection and gateway.
 * Call during process shutdown.
 */
function closeGateway() {
  if (_gateway) { _gateway.close(); _gateway = null; }
  if (_client)  { _client.close();  _client  = null; }
  console.log('[Fabric] Gateway closed.');
}

module.exports = { getContract, closeGateway };
